### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by frankwei98** [frankwei98/wechat-waifu-bot#1]
- [x] `Waifu` as an Object (Object-oriented programming)
- [x] Support konachan
- [ ] Saving waifu photo as cache instead of saving photo locally
- [ ] Bot enhancement like throwing error
- [ ] Telegram Version
- [x] Add `site` attribute in `Waifu` object
- [x] Shipping photo, not link
- [x] Shipping photo randomly

**Comment by frankwei98** [comment]
Shipping photo randomly was done in https://github.com/frankwei98/wechat-waifu-bot/commit/d93ac4d64a358fbd0802c831d9760f3b7f321c8d
